// Generated by gencpp from file youibot_msgs/ObjectGeneralInfo60BMultiArray.msg
// DO NOT EDIT!


#ifndef YOUIBOT_MSGS_MESSAGE_OBJECTGENERALINFO60BMULTIARRAY_H
#define YOUIBOT_MSGS_MESSAGE_OBJECTGENERALINFO60BMULTIARRAY_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <youibot_msgs/ObjectGeneralInfo60B.h>

namespace youibot_msgs
{
template <class ContainerAllocator>
struct ObjectGeneralInfo60BMultiArray_
{
  typedef ObjectGeneralInfo60BMultiArray_<ContainerAllocator> Type;

  ObjectGeneralInfo60BMultiArray_()
    : data()  {
    }
  ObjectGeneralInfo60BMultiArray_(const ContainerAllocator& _alloc)
    : data(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector< ::youibot_msgs::ObjectGeneralInfo60B_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::youibot_msgs::ObjectGeneralInfo60B_<ContainerAllocator> >::other >  _data_type;
  _data_type data;





  typedef boost::shared_ptr< ::youibot_msgs::ObjectGeneralInfo60BMultiArray_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::youibot_msgs::ObjectGeneralInfo60BMultiArray_<ContainerAllocator> const> ConstPtr;

}; // struct ObjectGeneralInfo60BMultiArray_

typedef ::youibot_msgs::ObjectGeneralInfo60BMultiArray_<std::allocator<void> > ObjectGeneralInfo60BMultiArray;

typedef boost::shared_ptr< ::youibot_msgs::ObjectGeneralInfo60BMultiArray > ObjectGeneralInfo60BMultiArrayPtr;
typedef boost::shared_ptr< ::youibot_msgs::ObjectGeneralInfo60BMultiArray const> ObjectGeneralInfo60BMultiArrayConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::youibot_msgs::ObjectGeneralInfo60BMultiArray_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::youibot_msgs::ObjectGeneralInfo60BMultiArray_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace youibot_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'actionlib_msgs': ['/opt/ros/kinetic/share/actionlib_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'youibot_msgs': ['/home/zjq/VLP_ws/src/youibot_msgs/msg', '/home/zjq/VLP_ws/devel/share/youibot_msgs/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::youibot_msgs::ObjectGeneralInfo60BMultiArray_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::youibot_msgs::ObjectGeneralInfo60BMultiArray_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::youibot_msgs::ObjectGeneralInfo60BMultiArray_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::youibot_msgs::ObjectGeneralInfo60BMultiArray_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::youibot_msgs::ObjectGeneralInfo60BMultiArray_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::youibot_msgs::ObjectGeneralInfo60BMultiArray_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::youibot_msgs::ObjectGeneralInfo60BMultiArray_<ContainerAllocator> >
{
  static const char* value()
  {
    return "2b2b8164badbb1bb1fbeb5f566080a39";
  }

  static const char* value(const ::youibot_msgs::ObjectGeneralInfo60BMultiArray_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x2b2b8164badbb1bbULL;
  static const uint64_t static_value2 = 0x1fbeb5f566080a39ULL;
};

template<class ContainerAllocator>
struct DataType< ::youibot_msgs::ObjectGeneralInfo60BMultiArray_<ContainerAllocator> >
{
  static const char* value()
  {
    return "youibot_msgs/ObjectGeneralInfo60BMultiArray";
  }

  static const char* value(const ::youibot_msgs::ObjectGeneralInfo60BMultiArray_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::youibot_msgs::ObjectGeneralInfo60BMultiArray_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# std_msgs/MultiArrayLayout layout\n\
ObjectGeneralInfo60B[] data #ObjectGeneralInfo60B array\n\
\n\
================================================================================\n\
MSG: youibot_msgs/ObjectGeneralInfo60B\n\
# This is a message to hold data from an BMS\n\
\n\
Header header\n\
int32 object_id 		  #Object ID (since objects are tracked, the ID is kept\n\
					  	  #throughout measurement cycles and does not have to be consecutive)\n\
float32 longitude_dist    #Longitudinal(x) coordinate\n\
float32 lateral_dist      #Lateral(y) coordinate\n\
float32 longitude_vel     #Relative velocity in longitudinal direction (x)\n\
float32 lateral_vel       #Relative velocity in lateral direction (y)\n\
std_msgs/String  object_dynprop    #Dynamic property of the object indicating if the object is\n\
					      #moving or stationary (this value can only be determined\n\
						  #correctly if the speed and yaw rate is given correctly)\n\
float32 rcs      	      #Radar cross section\n\
\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
\n\
================================================================================\n\
MSG: std_msgs/String\n\
string data\n\
";
  }

  static const char* value(const ::youibot_msgs::ObjectGeneralInfo60BMultiArray_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::youibot_msgs::ObjectGeneralInfo60BMultiArray_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.data);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ObjectGeneralInfo60BMultiArray_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::youibot_msgs::ObjectGeneralInfo60BMultiArray_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::youibot_msgs::ObjectGeneralInfo60BMultiArray_<ContainerAllocator>& v)
  {
    s << indent << "data[]" << std::endl;
    for (size_t i = 0; i < v.data.size(); ++i)
    {
      s << indent << "  data[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::youibot_msgs::ObjectGeneralInfo60B_<ContainerAllocator> >::stream(s, indent + "    ", v.data[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // YOUIBOT_MSGS_MESSAGE_OBJECTGENERALINFO60BMULTIARRAY_H
