// Generated by gencpp from file youibot_msgs/RobotTemp.msg
// DO NOT EDIT!


#ifndef YOUIBOT_MSGS_MESSAGE_ROBOTTEMP_H
#define YOUIBOT_MSGS_MESSAGE_ROBOTTEMP_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace youibot_msgs
{
template <class ContainerAllocator>
struct RobotTemp_
{
  typedef RobotTemp_<ContainerAllocator> Type;

  RobotTemp_()
    : header()
    , temp_0(0.0)
    , temp_1(0.0)
    , temp_2(0.0)
    , temp_3(0.0)
    , temp_4(0.0)
    , temp_5(0.0)
    , temp_6(0.0)  {
    }
  RobotTemp_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , temp_0(0.0)
    , temp_1(0.0)
    , temp_2(0.0)
    , temp_3(0.0)
    , temp_4(0.0)
    , temp_5(0.0)
    , temp_6(0.0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef float _temp_0_type;
  _temp_0_type temp_0;

   typedef float _temp_1_type;
  _temp_1_type temp_1;

   typedef float _temp_2_type;
  _temp_2_type temp_2;

   typedef float _temp_3_type;
  _temp_3_type temp_3;

   typedef float _temp_4_type;
  _temp_4_type temp_4;

   typedef float _temp_5_type;
  _temp_5_type temp_5;

   typedef float _temp_6_type;
  _temp_6_type temp_6;





  typedef boost::shared_ptr< ::youibot_msgs::RobotTemp_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::youibot_msgs::RobotTemp_<ContainerAllocator> const> ConstPtr;

}; // struct RobotTemp_

typedef ::youibot_msgs::RobotTemp_<std::allocator<void> > RobotTemp;

typedef boost::shared_ptr< ::youibot_msgs::RobotTemp > RobotTempPtr;
typedef boost::shared_ptr< ::youibot_msgs::RobotTemp const> RobotTempConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::youibot_msgs::RobotTemp_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::youibot_msgs::RobotTemp_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace youibot_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': True}
// {'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'actionlib_msgs': ['/opt/ros/kinetic/share/actionlib_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'youibot_msgs': ['/home/zjq/VLP_ws/src/youibot_msgs/msg', '/home/zjq/VLP_ws/devel/share/youibot_msgs/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::youibot_msgs::RobotTemp_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::youibot_msgs::RobotTemp_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::youibot_msgs::RobotTemp_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::youibot_msgs::RobotTemp_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::youibot_msgs::RobotTemp_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::youibot_msgs::RobotTemp_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::youibot_msgs::RobotTemp_<ContainerAllocator> >
{
  static const char* value()
  {
    return "f253c24a129534e63881b254d651ea62";
  }

  static const char* value(const ::youibot_msgs::RobotTemp_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xf253c24a129534e6ULL;
  static const uint64_t static_value2 = 0x3881b254d651ea62ULL;
};

template<class ContainerAllocator>
struct DataType< ::youibot_msgs::RobotTemp_<ContainerAllocator> >
{
  static const char* value()
  {
    return "youibot_msgs/RobotTemp";
  }

  static const char* value(const ::youibot_msgs::RobotTemp_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::youibot_msgs::RobotTemp_<ContainerAllocator> >
{
  static const char* value()
  {
    return "###### MESSAGE ######\n\
\n\
Header header\n\
\n\
float32 temp_0\n\
float32 temp_1\n\
float32 temp_2\n\
float32 temp_3\n\
float32 temp_4\n\
float32 temp_5\n\
float32 temp_6\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
";
  }

  static const char* value(const ::youibot_msgs::RobotTemp_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::youibot_msgs::RobotTemp_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.temp_0);
      stream.next(m.temp_1);
      stream.next(m.temp_2);
      stream.next(m.temp_3);
      stream.next(m.temp_4);
      stream.next(m.temp_5);
      stream.next(m.temp_6);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct RobotTemp_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::youibot_msgs::RobotTemp_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::youibot_msgs::RobotTemp_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "temp_0: ";
    Printer<float>::stream(s, indent + "  ", v.temp_0);
    s << indent << "temp_1: ";
    Printer<float>::stream(s, indent + "  ", v.temp_1);
    s << indent << "temp_2: ";
    Printer<float>::stream(s, indent + "  ", v.temp_2);
    s << indent << "temp_3: ";
    Printer<float>::stream(s, indent + "  ", v.temp_3);
    s << indent << "temp_4: ";
    Printer<float>::stream(s, indent + "  ", v.temp_4);
    s << indent << "temp_5: ";
    Printer<float>::stream(s, indent + "  ", v.temp_5);
    s << indent << "temp_6: ";
    Printer<float>::stream(s, indent + "  ", v.temp_6);
  }
};

} // namespace message_operations
} // namespace ros

#endif // YOUIBOT_MSGS_MESSAGE_ROBOTTEMP_H
