// Generated by gencpp from file youibot_msgs/SensorState.msg
// DO NOT EDIT!


#ifndef YOUIBOT_MSGS_MESSAGE_SENSORSTATE_H
#define YOUIBOT_MSGS_MESSAGE_SENSORSTATE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace youibot_msgs
{
template <class ContainerAllocator>
struct SensorState_
{
  typedef SensorState_<ContainerAllocator> Type;

  SensorState_()
    : header()
    , time_stamp(0)
    , encoder()
    , speed()
    , current()
    , over_current(0)
    , digital_input(0)
    , analog_input()  {
    }
  SensorState_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , time_stamp(0)
    , encoder(_alloc)
    , speed(_alloc)
    , current(_alloc)
    , over_current(0)
    , digital_input(0)
    , analog_input(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef uint16_t _time_stamp_type;
  _time_stamp_type time_stamp;

   typedef std::vector<int32_t, typename ContainerAllocator::template rebind<int32_t>::other >  _encoder_type;
  _encoder_type encoder;

   typedef std::vector<int16_t, typename ContainerAllocator::template rebind<int16_t>::other >  _speed_type;
  _speed_type speed;

   typedef std::vector<int16_t, typename ContainerAllocator::template rebind<int16_t>::other >  _current_type;
  _current_type current;

   typedef uint8_t _over_current_type;
  _over_current_type over_current;

   typedef uint16_t _digital_input_type;
  _digital_input_type digital_input;

   typedef std::vector<uint16_t, typename ContainerAllocator::template rebind<uint16_t>::other >  _analog_input_type;
  _analog_input_type analog_input;





  typedef boost::shared_ptr< ::youibot_msgs::SensorState_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::youibot_msgs::SensorState_<ContainerAllocator> const> ConstPtr;

}; // struct SensorState_

typedef ::youibot_msgs::SensorState_<std::allocator<void> > SensorState;

typedef boost::shared_ptr< ::youibot_msgs::SensorState > SensorStatePtr;
typedef boost::shared_ptr< ::youibot_msgs::SensorState const> SensorStateConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::youibot_msgs::SensorState_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::youibot_msgs::SensorState_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace youibot_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': True}
// {'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'actionlib_msgs': ['/opt/ros/kinetic/share/actionlib_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'youibot_msgs': ['/home/zjq/VLP_ws/src/youibot_msgs/msg', '/home/zjq/VLP_ws/devel/share/youibot_msgs/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::youibot_msgs::SensorState_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::youibot_msgs::SensorState_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::youibot_msgs::SensorState_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::youibot_msgs::SensorState_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::youibot_msgs::SensorState_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::youibot_msgs::SensorState_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::youibot_msgs::SensorState_<ContainerAllocator> >
{
  static const char* value()
  {
    return "5a7cb49d0bca5d78148281346d72c02f";
  }

  static const char* value(const ::youibot_msgs::SensorState_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x5a7cb49d0bca5d78ULL;
  static const uint64_t static_value2 = 0x148281346d72c02fULL;
};

template<class ContainerAllocator>
struct DataType< ::youibot_msgs::SensorState_<ContainerAllocator> >
{
  static const char* value()
  {
    return "youibot_msgs/SensorState";
  }

  static const char* value(const ::youibot_msgs::SensorState_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::youibot_msgs::SensorState_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# Youibot Sensor Data Messages\n\
#\n\
# For more direct simple interactions (buttons, leds, gyro, motor velocity\n\
# etc) use the other topics. This provides detailed information about the\n\
# entire state package that is transmitted at 50Hz from the robot.\n\
#\n\
\n\
###### MESSAGE ######\n\
\n\
Header header\n\
\n\
###################\n\
# Core Packet\n\
###################\n\
uint16 time_stamp      # milliseconds starting when turning on Kobuki (max. 65536, then starts from 0 again)\n\
int32[]  encoder    # accumulated ticks left wheel starting with turning on Kobuki (max. 65535)\n\
int16[]  speed      # rpm\n\
\n\
###################\n\
# Current Packet\n\
###################\n\
int16[] current        # motor current for the left and right motor in mA\n\
uint8   over_current   # see over current states\n\
\n\
###################\n\
# Input Packet\n\
###################\n\
uint16   digital_input # see digital input states; will show garbage when nothing is connected\n\
uint16[] analog_input  # ADC values for the 4 analog inputs; 0 - 4095: 0.0 - 3.3V; will show garbage when nothing is connected\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
";
  }

  static const char* value(const ::youibot_msgs::SensorState_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::youibot_msgs::SensorState_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.time_stamp);
      stream.next(m.encoder);
      stream.next(m.speed);
      stream.next(m.current);
      stream.next(m.over_current);
      stream.next(m.digital_input);
      stream.next(m.analog_input);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SensorState_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::youibot_msgs::SensorState_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::youibot_msgs::SensorState_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "time_stamp: ";
    Printer<uint16_t>::stream(s, indent + "  ", v.time_stamp);
    s << indent << "encoder[]" << std::endl;
    for (size_t i = 0; i < v.encoder.size(); ++i)
    {
      s << indent << "  encoder[" << i << "]: ";
      Printer<int32_t>::stream(s, indent + "  ", v.encoder[i]);
    }
    s << indent << "speed[]" << std::endl;
    for (size_t i = 0; i < v.speed.size(); ++i)
    {
      s << indent << "  speed[" << i << "]: ";
      Printer<int16_t>::stream(s, indent + "  ", v.speed[i]);
    }
    s << indent << "current[]" << std::endl;
    for (size_t i = 0; i < v.current.size(); ++i)
    {
      s << indent << "  current[" << i << "]: ";
      Printer<int16_t>::stream(s, indent + "  ", v.current[i]);
    }
    s << indent << "over_current: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.over_current);
    s << indent << "digital_input: ";
    Printer<uint16_t>::stream(s, indent + "  ", v.digital_input);
    s << indent << "analog_input[]" << std::endl;
    for (size_t i = 0; i < v.analog_input.size(); ++i)
    {
      s << indent << "  analog_input[" << i << "]: ";
      Printer<uint16_t>::stream(s, indent + "  ", v.analog_input[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // YOUIBOT_MSGS_MESSAGE_SENSORSTATE_H
