// Generated by gencpp from file youibot_msgs/WayPoints.msg
// DO NOT EDIT!


#ifndef YOUIBOT_MSGS_MESSAGE_WAYPOINTS_H
#define YOUIBOT_MSGS_MESSAGE_WAYPOINTS_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <geometry_msgs/PoseArray.h>

namespace youibot_msgs
{
template <class ContainerAllocator>
struct WayPoints_
{
  typedef WayPoints_<ContainerAllocator> Type;

  WayPoints_()
    : header()
    , ways(0)
    , cancel(0)
    , poses()  {
    }
  WayPoints_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , ways(0)
    , cancel(0)
    , poses(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef int16_t _ways_type;
  _ways_type ways;

   typedef int16_t _cancel_type;
  _cancel_type cancel;

   typedef  ::geometry_msgs::PoseArray_<ContainerAllocator>  _poses_type;
  _poses_type poses;





  typedef boost::shared_ptr< ::youibot_msgs::WayPoints_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::youibot_msgs::WayPoints_<ContainerAllocator> const> ConstPtr;

}; // struct WayPoints_

typedef ::youibot_msgs::WayPoints_<std::allocator<void> > WayPoints;

typedef boost::shared_ptr< ::youibot_msgs::WayPoints > WayPointsPtr;
typedef boost::shared_ptr< ::youibot_msgs::WayPoints const> WayPointsConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::youibot_msgs::WayPoints_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::youibot_msgs::WayPoints_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace youibot_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': True}
// {'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'actionlib_msgs': ['/opt/ros/kinetic/share/actionlib_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'youibot_msgs': ['/home/zjq/VLP_ws/src/youibot_msgs/msg', '/home/zjq/VLP_ws/devel/share/youibot_msgs/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::youibot_msgs::WayPoints_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::youibot_msgs::WayPoints_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::youibot_msgs::WayPoints_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::youibot_msgs::WayPoints_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::youibot_msgs::WayPoints_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::youibot_msgs::WayPoints_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::youibot_msgs::WayPoints_<ContainerAllocator> >
{
  static const char* value()
  {
    return "695863f948eb99baac47773850b70a3a";
  }

  static const char* value(const ::youibot_msgs::WayPoints_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x695863f948eb99baULL;
  static const uint64_t static_value2 = 0xac47773850b70a3aULL;
};

template<class ContainerAllocator>
struct DataType< ::youibot_msgs::WayPoints_<ContainerAllocator> >
{
  static const char* value()
  {
    return "youibot_msgs/WayPoints";
  }

  static const char* value(const ::youibot_msgs::WayPoints_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::youibot_msgs::WayPoints_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n\
int16  ways  # 1: Routine inspection ; 0: Special inspection ; 2: Auto Docking\n\
int16  cancel # 1: cancel; 0: normal\n\
geometry_msgs/PoseArray poses # The waypoints\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
\n\
================================================================================\n\
MSG: geometry_msgs/PoseArray\n\
# An array of poses with a header for global reference.\n\
\n\
Header header\n\
\n\
Pose[] poses\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Pose\n\
# A representation of pose in free space, composed of position and orientation. \n\
Point position\n\
Quaternion orientation\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Point\n\
# This contains the position of a point in free space\n\
float64 x\n\
float64 y\n\
float64 z\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Quaternion\n\
# This represents an orientation in free space in quaternion form.\n\
\n\
float64 x\n\
float64 y\n\
float64 z\n\
float64 w\n\
";
  }

  static const char* value(const ::youibot_msgs::WayPoints_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::youibot_msgs::WayPoints_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.ways);
      stream.next(m.cancel);
      stream.next(m.poses);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct WayPoints_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::youibot_msgs::WayPoints_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::youibot_msgs::WayPoints_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "ways: ";
    Printer<int16_t>::stream(s, indent + "  ", v.ways);
    s << indent << "cancel: ";
    Printer<int16_t>::stream(s, indent + "  ", v.cancel);
    s << indent << "poses: ";
    s << std::endl;
    Printer< ::geometry_msgs::PoseArray_<ContainerAllocator> >::stream(s, indent + "  ", v.poses);
  }
};

} // namespace message_operations
} // namespace ros

#endif // YOUIBOT_MSGS_MESSAGE_WAYPOINTS_H
