# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from youibot_msgs/StatusEvent.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import std_msgs.msg

class StatusEvent(genpy.Message):
  _md5sum = "1bbf73ac587662abfa23af50085fd630"
  _type = "youibot_msgs/StatusEvent"
  _has_header = True #flag to mark the presence of a Header object
  _full_text = """###### MESSAGE ######

Header header

uint8 ERROR  = 1
uint8 NORMAL = 0

# 心跳报文超时
uint8 Msg_Timeout
# 驱动器报错
uint8 Kinco_Alert
# 前保险杠碰撞
uint8 Front_Bumper
# 后保险杠碰撞
uint8 Back_Bumper
# 按钮急停
uint8 Button_Stop
# 无线急停
uint8 Wlan_Stop
# 网络急停
uint8 Net_Stop
# 电池报错
uint8 powerStatus
# 语音报错
uint8 Audio_Alert

================================================================================
MSG: std_msgs/Header
# Standard metadata for higher-level stamped data types.
# This is generally used to communicate timestamped data 
# in a particular coordinate frame.
# 
# sequence ID: consecutively increasing ID 
uint32 seq
#Two-integer timestamp that is expressed as:
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')
# time-handling sugar is provided by the client library
time stamp
#Frame this data is associated with
# 0: no frame
# 1: global frame
string frame_id
"""
  # Pseudo-constants
  ERROR = 1
  NORMAL = 0

  __slots__ = ['header','Msg_Timeout','Kinco_Alert','Front_Bumper','Back_Bumper','Button_Stop','Wlan_Stop','Net_Stop','powerStatus','Audio_Alert']
  _slot_types = ['std_msgs/Header','uint8','uint8','uint8','uint8','uint8','uint8','uint8','uint8','uint8']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       header,Msg_Timeout,Kinco_Alert,Front_Bumper,Back_Bumper,Button_Stop,Wlan_Stop,Net_Stop,powerStatus,Audio_Alert

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(StatusEvent, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.header is None:
        self.header = std_msgs.msg.Header()
      if self.Msg_Timeout is None:
        self.Msg_Timeout = 0
      if self.Kinco_Alert is None:
        self.Kinco_Alert = 0
      if self.Front_Bumper is None:
        self.Front_Bumper = 0
      if self.Back_Bumper is None:
        self.Back_Bumper = 0
      if self.Button_Stop is None:
        self.Button_Stop = 0
      if self.Wlan_Stop is None:
        self.Wlan_Stop = 0
      if self.Net_Stop is None:
        self.Net_Stop = 0
      if self.powerStatus is None:
        self.powerStatus = 0
      if self.Audio_Alert is None:
        self.Audio_Alert = 0
    else:
      self.header = std_msgs.msg.Header()
      self.Msg_Timeout = 0
      self.Kinco_Alert = 0
      self.Front_Bumper = 0
      self.Back_Bumper = 0
      self.Button_Stop = 0
      self.Wlan_Stop = 0
      self.Net_Stop = 0
      self.powerStatus = 0
      self.Audio_Alert = 0

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_3I().pack(_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs))
      _x = self.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.pack('<I%ss'%length, length, _x))
      _x = self
      buff.write(_get_struct_9B().pack(_x.Msg_Timeout, _x.Kinco_Alert, _x.Front_Bumper, _x.Back_Bumper, _x.Button_Stop, _x.Wlan_Stop, _x.Net_Stop, _x.powerStatus, _x.Audio_Alert))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      if self.header is None:
        self.header = std_msgs.msg.Header()
      end = 0
      _x = self
      start = end
      end += 12
      (_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs,) = _get_struct_3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.header.frame_id = str[start:end].decode('utf-8')
      else:
        self.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 9
      (_x.Msg_Timeout, _x.Kinco_Alert, _x.Front_Bumper, _x.Back_Bumper, _x.Button_Stop, _x.Wlan_Stop, _x.Net_Stop, _x.powerStatus, _x.Audio_Alert,) = _get_struct_9B().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_3I().pack(_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs))
      _x = self.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.pack('<I%ss'%length, length, _x))
      _x = self
      buff.write(_get_struct_9B().pack(_x.Msg_Timeout, _x.Kinco_Alert, _x.Front_Bumper, _x.Back_Bumper, _x.Button_Stop, _x.Wlan_Stop, _x.Net_Stop, _x.powerStatus, _x.Audio_Alert))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      if self.header is None:
        self.header = std_msgs.msg.Header()
      end = 0
      _x = self
      start = end
      end += 12
      (_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs,) = _get_struct_3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.header.frame_id = str[start:end].decode('utf-8')
      else:
        self.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 9
      (_x.Msg_Timeout, _x.Kinco_Alert, _x.Front_Bumper, _x.Back_Bumper, _x.Button_Stop, _x.Wlan_Stop, _x.Net_Stop, _x.powerStatus, _x.Audio_Alert,) = _get_struct_9B().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_3I = None
def _get_struct_3I():
    global _struct_3I
    if _struct_3I is None:
        _struct_3I = struct.Struct("<3I")
    return _struct_3I
_struct_9B = None
def _get_struct_9B():
    global _struct_9B
    if _struct_9B is None:
        _struct_9B = struct.Struct("<9B")
    return _struct_9B
