Header header

# type 0 STK001-0B / STK001-0A
float32[] server_STK

# type 1 STL001-0A
float32[] server_STL

# type 2 SGC001-1B
float32[] server_seal_co2

# type 3 SGC001-1A
float32[] server_non_seal_co2

# type 4 O2
float32[] server_O2

# type 5 SE6IN1-0A

float32 server_6_temperature_type5
float32 server_6_humidity_type5
float32 server_6_pressure_type5
float32 server_6_o2_type5
float32 server_6_tvoc_type5
float32 server_6_pm25_type5

# type 6

# type 7 gate signal
int8[] server_gate
