(cl:in-package youibot_msgs-msg)
(cl:export '(HEADER-VAL
          HEADER
          SERVER_STK-VAL
          SERVER_STK
          SERVER_STL-VAL
          SERVER_STL
          SERVER_SEAL_CO2-VAL
          SERVER_SEAL_CO2
          SERVER_NON_SEAL_CO2-VAL
          SERVER_NON_SEAL_CO2
          SERVER_O2-VAL
          SERVER_O2
          SERVER_6_TEMPERATURE_TYPE5-VAL
          SERVER_6_TEMPERATURE_TYPE5
          SERVER_6_HUMIDITY_TYPE5-VAL
          SERVER_6_HUMIDITY_TYPE5
          SERVER_6_PRESSURE_TYPE5-VAL
          SERVER_6_PRESSURE_TYPE5
          SERVER_6_O2_TYPE5-VAL
          SERVER_6_O2_TYPE5
          SERVER_6_TVOC_TYPE5-VAL
          SERVER_6_TVOC_TYPE5
          SERVER_6_PM25_TYPE5-VAL
          SERVER_6_PM25_TYPE5
          SERVER_GATE-VAL
          SERVER_GATE
))